from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from enum import Enum
import operator
from typing_extensions import Annotated

class ApprovalStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING = "PENDING"

class InvestorType(str, Enum):
    INTRADAY = "INTRADAY"
    SHORT_TERM = "SHORT_TERM"
    LONG_TERM = "LONG_TERM"

class UserRequest(BaseModel):
    asset_class: str
    risk_tolerance: str
    time_horizon: str
    investor_type: InvestorType = InvestorType.LONG_TERM
    tickers: List[str] = Field(default_factory=lambda: ["AAPL"])
    additional_constraints: Optional[str] = None

class MarketContext(BaseModel):
    macro_data: Dict[str, Any] = Field(default_factory=dict)
    micro_data: Dict[str, Any] = Field(default_factory=dict)

class AgentObservations(BaseModel):
    fundamental: Optional[Dict[str, Any]] = None
    quantitative: Optional[Dict[str, Any]] = None
    alternative: Optional[Dict[str, Any]] = None
    macroeconomic: Optional[Dict[str, Any]] = None
    sentiment: Optional[Dict[str, Any]] = None

class PortfolioState(BaseModel):
    holdings: Dict[str, float] = Field(default_factory=dict)
    buying_power: float = 0.0

class DiscoveredSignals(BaseModel):
    signals: List[Dict[str, Any]] = Field(default_factory=list)

class DraftStrategy(BaseModel):
    strategy_id: str
    rationale: str
    parameters: Dict[str, Any]
    target_allocations: Dict[str, float]

def merge_observations(left: AgentObservations, right: Dict[str, Any]) -> AgentObservations:
    """Reducer to merge parallel observation updates into the AgentObservations model."""
    # Convert left to dict if it's already a model, or use it as is
    base_data = left.model_dump() if isinstance(left, AgentObservations) else left
    
    # Merge the new data (right) into the base data
    # Note: right is usually the partial update from a node: {"fundamental": {...}}
    if isinstance(right, AgentObservations):
        new_data = right.model_dump(exclude_unset=True)
    elif isinstance(right, dict):
        new_data = right
    else:
        return left

    base_data.update(new_data)
    return AgentObservations(**base_data)

class ADKState(BaseModel):
    request: UserRequest
    context: MarketContext = Field(default_factory=MarketContext)
    observations: Annotated[AgentObservations, merge_observations] = Field(default_factory=AgentObservations)
    signals: DiscoveredSignals = Field(default_factory=DiscoveredSignals)
    portfolio: PortfolioState = Field(default_factory=PortfolioState)
    draft_strategy: Optional[DraftStrategy] = None
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    # Annotated list to append feedback during the Critic Loop
    feedback_loop: Annotated[List[str], operator.add] = Field(default_factory=list)
    final_report: Optional[str] = None
    backtest_results: Optional[Dict[str, Any]] = None
    # Self-Correction & Monitoring
    backtest_attempts: int = 0
    max_backtest_retries: int = 2
    execution_logs: List[str] = Field(default_factory=list)
    metrics_log: Dict[str, Any] = Field(default_factory=dict)
    # Institutional Upgrades (ADK v4.0)
    ensemble_sub_strategies: Dict[str, DraftStrategy] = Field(default_factory=dict)
    stress_test_report: Optional[Dict[str, Any]] = None
    long_term_memory: List[Dict[str, Any]] = Field(default_factory=list)
    system_instructions: Dict[str, str] = Field(default_factory=dict)
    # Actionable checklist generated by the Planner
    plan: List[str] = Field(default_factory=list)
    # Retry counter to prevent infinite Critic loops
    current_retry: int = 0
    max_retries: int = 3
